### ISSUE TITLE
Simultaneously switching of layouts in emacs and the system

### ISSUE THREAD

**Issue by ghost** [Mihara/kbd-indicator.el#1]
Hi Eugene,

Thank you for your program. The idea is really nice. Although  it somehow works incorrectly on my systems (emacs 26.0.90 + ubuntu 17.10 or emacs 25.3 + ubuntu 17.04) Namely, sometimes  i switch the layout in emacs, sometimes in the system:
Emacs : En->En->Ru->Ru->En......
System: En->Ru->En->Ru->En.....

Could you help me to fix it?

**Comment by Mihara** [comment]
Yeah, I noticed this myself, but haven't had a free moment to figure out why just yet.

I'll fix it soon, hopefully. :)

**Comment by Mihara** [comment]
There, that *should* be it. Please reopen this issue if this doesn't work for you, although, finding out what's going on is going to be difficult in this case.

Background of the issue is like this:

* Only ubuntu's keyboard-indicator seems to let you listen to a language change event. I don't know of any other methods, and nothing *else* seems to turn up on `dbus-monitor` when I switch languages -- except events generated by keyboard-indicator. So this mode registers to listen for them.
* Once an event comes in, the mode needs to switch the system language back. But of course this results in *another* language change event, and there is no way to tell *what* originated the event, -- we're basically listening to a distant echo of something we triggered through an entirely different subsystem, keyboard-indicator won't tell us what caused it to switch -- so we can't just filter the events we caused.
* Which is why the code sets a flag to skip exactly one language change event.

Now, if it somehow manages to never receive the language change event that it caused, this results in the behavior you described. After some manner of system change -- I wish I knew whether it was in Ubuntu or in Emacs -- this would happen often, but annoyingly, not *all* the time, so I couldn't just cut out the flag and move on.

I'm blaming the Emacs dbus api, because I don't remember `dbus-call-method-asynchronously` being there before, but I might just be imagining things. In any case, it appears to be working fine for me now.

**Comment by ghost** [comment]
Thank you . It works
